---
recipes:
  - "aaf"
  - "aaplus"
  - "abseil"
  - "access_private"
  - "acl"
  - "ade"
  - "aeron"
  - "alac"
  - "alembic"
  - "alpaca"
  - "amgcl"
  - "amqp-cpp"
  - "android-ndk"
  - "angelscript"
  - "antlr4-cppruntime"
  - "any-lite"
  - "anyrpc"
  - "apr"
  - "aravis"
  - "archicad-apidevkit"
  - "arcus"
  - "arduinojson"
  - "argh"
  - "argon2"
  - "argparse"
  - "args-parser"
  - "argtable2"
  - "argtable3"
  - "armadillo"
  - "arrow"
  - "arsenalgear"
  - "aruco"
  - "asio-grpc"
  - "asio"
  - "asmjit"
  - "assimp"
  - "astc-codec"
  - "asyncplusplus"
  - "at-spi2-core":
    - folders: ["new"]
  - "atk"
  - "audiofile"
  - "autoconf-archive"
  - "autoconf"
  - "automake"
  - "avahi"
  - "avcpp"
  - "avir"
  - "aws-c-auth"
  - "aws-c-cal"
  - "aws-c-common"
  - "aws-c-compression"
  - "aws-c-event-stream"
  - "aws-c-http"
  - "aws-c-io"
  - "aws-c-mqtt"
  - "aws-c-s3"
  - "aws-c-sdkutils"
  - "aws-checksums"
  - "aws-crt-cpp"
  - b2: # Needed by boost
     - folders: ["portable"]
  - "backport-cpp"
  - "backward-cpp"
  - "bacnet-stack"
  - "baical-p7"
  - "bandit"
  - "base64"
  - "bdwgc"
  - "bear"
  - "beauty"
  - "behaviortree.cpp"
  - "benchmark"
  - "bertrand"
  - "bigint"
  - "bimg"
  - "binutils"
  - "bison"
  - "bit-lite"
  - "bitflags"
  - "bitmagic"
  - "bitserializer"
  - "bitsery"
  - "blaze"
  - "blend2d"
  - "boolean-lite"
  - "boolinq"
  - "boost-ext-ut"
  - "boost-leaf"
  - "boost"
  - "box2d"
  - "box2d"
  - "breakpad"
  - "brigand"
  - "brotli"
  - "brynet"
  - "bshoshany-thread-pool"
  - "bullet3"
  - "butteraugli"
  - "bvdberg-ctest"
  - "bx"
  - "byte-lite"
  - "bzip2"
  - "bzip3"
  - "c-ares"
  - "c-blosc"
  - "c-blosc2"
  - "c-client"
  - "c-dbg-macro"
  - "c4core"
  - "caf"
  - "cairo"
  - "cairo"
  - "cajun-jsonapi"
  - "calceph"
  - "canary"
  - "canvas_ity"
  - "capnproto"
  - "capstone"
  - "catch2"
  - "catch2"
  - "cccl"
  - "ccfits"
  - "cctag"
  - "cctz"
  - "cd3-boost-unit-definitions"
  - "celero"
  - "cereal"
  - "cfgfile"
  - "cgns"
  - "charls"
  - "chipmunk2d"
  - "cimg"
  - "circularbuffer"
  - "cista"
  - "cityhash"
  - "civetweb"
  - "cjson"
  - "clara"
  - "clhep"
  - "cli11"
  - "clipp"
  - "clipper"
  - "cmake"
  - "cminpack"
  - "cmocka"
  - "cmp"
  - "cnpy"
  - "cocoyaxi"
  - "coin-lemon"
  - "coin-osi"
  - "coin-utils"
  - "commata"
  - "concurrencpp"
  - "concurrentqueue"
  - "confu_json"
  - "cpp-httplib"
  - "cpp-jwt"
  - "cpp-lazy"
  - "cpp-optparse"
  - "cpp-peglib"
  - "cpp-peglib"
  - "cpp-sort"
  - "cppbenchmark"
  - "cppcheck"
  - "cppcodec"
  - "cppfront"
  - "cppkafka"
  - "cpprestsdk"
  - "cppserver"
  - "cpptoml"
  - "cppunit"
  - "cpputest"
  - "cppzmq"
  - "cpr"
  - "cpu_features"
  - "cpuinfo"
  - "cqrlib"
  - "crc32c"
  - "crc_cpp"
  - "create-dmg"
  - "crowcpp-crow"
  - "crunch"
  - "cryptopp"
  - "cs_libguarded"
  - "cspice"
  - "csvmonkey"
  - "ctre"
  - "cwalk"
  - "cxxopts"
  - "cyclonedds"
  - "cyrus-sasl"
  - "czmq"
  - "dacap-clip"
  - "dataframe"
  - "date"
  - "dav1d"
  - "daw_header_libraries"
  - "daw_json_link"
  - "daw_utf_range"
  - "dbcppp"
  - "dbus"
  - "decimal_for_cpp"
  - "diligent-core"
  - "discount"
  - "docopt.cpp"
  - "doctest"
  - "double-conversion"
  - "doxygen"
  - "draco"
  - "dragonbox"
  - "drflac"
  - "drmp3"
  - "drogon"
  - "drwav"
  - "duckdb"
  - "easyexif"
  - "easyhttpcpp"
  - "ecos"
  - "edlib"
  - "edyn"
  - "egl-headers"
  - "egl"
  - "eigen"
  - "elfio"
  - "embree3"
  - "emsdk"
  - "enet"
  - "entityx"
  - "entt"
  - "enum-flags"
  - "erikzenker-hsm"
  - "erkir"
  - "eternal"
  - "etl"
  - "exiv2"
  - "expat"
  - "expected-lite"
  - "ezc3d"
  - "faac"
  - "farmhash"
  - "fast-cdr"
  - "fast-cpp-csv-parser"
  - "fast_double_parser"
  - "fast_float"
  - "fastpfor"
  - "fastprng"
  - "fcl"
  - "fft"
  - "fftw"
  - "flac"
  - "flann"
  - "flatbuffers"
  - "flecs"
  - "flex"
  - "fmt"
  - "fmtlog"
  - "fontconfig"
  - "fontconfig"
  - "foonathan-lexy"
  - "foonathan-memory"
  - "foxi"
  - "fp16"
  - "freeimage"
  - "freetype"
  - "freexl"
  - "fribidi"
  - "frozen"
  - "fruit"
  - "function2"
  - "functionalplus"
  - "fxdiv"
  - "g3log"
  - "gainput"
  - "gamma"
  - "gcc"
  - "gcem"
  - "gdal":
    - folders: ["pre_3.5.0"]
  - "gdcm"
  - "gdk-pixbuf"
  - "gemmlowp"
  - "genie"
  - "geographiclib"
  - "geos"
  - "geotrans"
  - "getopt-for-visual-studio"
  - "gettext"
  - "gflags"
  - "gfortran"
  - "ghc-filesystem"
  - "giflib":
    - folders: ["5.2.x"]
  - "glaze"
  - "glbinding"
  - "glew"
  - "glfw"
  - "glib"
  - "glibmm"
  - "glm"
  - "glog"
  - "glslang"
  - "glu"
  - "gmp"
  - "gnu-config"
  - "gnutls"
  - "godot_headers"
  - "googleapis"
  - "gperf"
  - "graphene"
  - "greg7mdp-gtl"
  - "grpc-proto"
  - "gsl-lite"
  - "gsl"
  - "gsoap"
  - "gtest"
  - "gtsam"
  - "gumbo-parser"
  - "gzip-hpp"
  - "h3"
  - "h5pp"
  - "half"
  - "hana"
  - "harfbuzz"
  - "hash-library"
  - "hazelcast-cpp-client"
  - "hdf5"
  - "hdrhistogram-c"
  - "heatshrink"
  - "hedley"
  - "hffix"
  - "hidapi"
  - "highfive"
  - "highs"
  - "highway"
  - "hiredis":
    - folders: ["all"]
  - "hlslpp"
  - "homog2d"
  - "http_parser"
  - "hyperscan"
  - "icu"
  - "iir1"
  - "imake"
  - "imath"
  - "imgui"
  - "imutils-cpp"
  - "indicators"
  - "inih"
  - "inja"
  - "innoextract"
  - "irrxml"
  - "iso8601lib"
  - "itlib"
  - "ittapi"
  - "ixwebsocket"
  - "jansson"
  - "jasper"
  - "jbig"
  - "jeaiii-itoa"
  - "jfalcou-eve"
  - "joltphysics"
  - "jom"
  - "jpeg-compressor"
  - "jsmn"
  - "json-c"
  - "json-schema-validator"
  - "json_dto"
  - "jsoncpp"
  - "jthread-lite"
  - "jwasm"
  - "jwt-cpp"
  - "jxrlib"
  - "kaitai_struct_cpp_stl_runtime"
  - "khrplatform"
  - "kissfft"
  - "kmod"
  - "kplot"
  - "kuba-zip"
  - "laszip"
  - "lcms"
  - "lely-core"
  - "leptonica"
  - "lerc"
  - "leveldb"
  - "libaec"
  - "libaio"
  - "libalsa"
  - "libaom-av1"
  - "libarchive"
  - "libatomic_ops"
  - "libavif"
  - "libavrocpp"
  - "libbacktrace"
  - "libbigwig"
  - "libbpf"
  - "libcap"
  - "libcbor"
  - "libccd"
  - "libcds"
  - "libconfig"
  - "libconfuse"
  - "libcorrect"
  - "libcurl"
  - "libdaemon"
  - "libdc1394"
  - "libde265"
  - "libdeflate"
  - "libdeflate"
  - "libdisasm"
  - "libdmtx"
  - "libdwarf"
  - "libdxfrw"
  - "libe57format"
  - "libelf"
  - "libev"
  - "libevent"
  - "libexif"
  - "libfdk_aac"
  - "libffi"
  - "libftdi":
    - folders: ["1.x"]
  - "libfuse"
  - "libfuse"
  - "libgcrypt"
  - "libgd"
  - "libgeotiff"
  - "libgettext"
  - "libglvnd"
  - "libhal"
  - "libharu"
  - "libheif"
  - "libhydrogen"
  - "libiberty"
  - "libiconv"
  - "libinterpolate"
  - "libjpeg-turbo"
  - "libjpeg"
  - "libmaxminddb"
  - "libmetalink"
  - "libmicrohttpd"
  - "libmodbus"
  - "libmorton"
  - "libmount"
  - "libmp3lame"
  - "libmysqlclient"
  - "libnet"
  - "libnfs"
  - "libnghttp2"
  - "libnoise"
  - "libnop"
  - "libnova"
  - "libnuma"
  - "libpcap"
  - "libpciaccess"
  - "libpfm4"
  - "libpng"
  - "libpq"
  - "libpqxx"
  - "libqrencode"
  - "libraw"
  - "librdkafka"
  - "librttopo"
  - "libsamplerate"
  - "libschrift"
  - "libselinux"
  - "libserial"
  - "libsgp4"
  - "libsigcpp"
  - "libsigcpp"
  - "libsmacker"
  - "libsndfile"
  - "libsodium"
  - "libspatialindex"
  - "libspng"
  - "libsquish"
  - "libstudxml":
    - folders: ["1.1.x"]
  - "libsvm"
  - "libsvtav1"
  - "libsystemd"
  - "libtar"
  - "libtasn1"
  - "libtiff"
  - "libtool"
  - "libtorrent"
  - "libucl"
  - "libunistring"
  - "libunwind"
  - "libusb"
  - "libuuid"
  - "libuv"
  - "libuvc"
  - "libvault"
  - "libverto"
  - "libvpx"
  - "libwebp"
  - "libxcrypt"
  - "libxls"
  - "libxlsxwriter"
  - "libxml2"
  - "libyaml"
  - "libyuv"
  - "libzen"
  - "libzip"
  - "libzippp"
  - "lief"
  - "linmath.h"
  - "litehtml"
  - "lmdb"
  - "lodepng"
  - "log.c"
  - "log4cplus"
  - "logr":
    - folders: ["all"]
  - "ls-qpack"
  - "lua"
  - "luajit"
  - "luau"
  - "lunasvg"
  - "luple"
  - "lurlparser"
  - "lyra"
  - "lz4"
  - "lzfse"
  - "lzham"
  - "lzo"
  - "m4"
  - "magic_enum"
  - "mailio"
  - "make"
  - "mapbox-geometry"
  - "mapbox-variant"
  - "mariadb-connector-c"
  - "matchit"
  - "mathfu"
  - "mbedtls"
  - "mbits-args"
  - "mbits-diags"
  - "mbits-mstch"
  - "mbits-semver"
  - "mbits-utfconv"
  - "mcap"
  - "md4c"
  - "md4qt"
  - "meshoptimizer"
  - "meson"
  - "metall"
  - "mfast"
  - "mgs"
  - "microtar"
  - "mikelankamp-fpm"
  - "mikktspace"
  - "mimalloc"
  - "miniaudio"
  - "minimp3"
  - "miniscript"
  - "minitrace"
  - "miniupnpc"
  - "miniz"
  - "minizip-ng"
  - "minizip"
  - "mio"
  - "modern-cpp-kafka"
  - "mold":
    - folders: ["all"]
  - "moltenvk"
  - "mongo-c-driver"
  - "mongo-cxx-driver"
  - "morton-nd"
  - "mosquitto":
    - folders: ["1.x"]
  - "mozilla-build"
  - "mozjpeg"
  - "mpark-variant"
  - "mpc"
  - "mpg123"
  - "mpmcqueue"
  - "mppp"
  - "ms-gsl"
  - "msdfgen"
  - "msgpack-c"
  - "msgpack-cxx"
  - "msys2"
  - "mujs"
  - "muparser"
  - "muparserx"
  - "nanobench"
  - "nanoflann"
  - "nanosvg"
  - "nas"
  - "nasm"
  - "netcdf"
  - "nettle"
  - "ninja"
  - "nlohmann_json"
  - "nlopt"
  - "nmos-cpp"
  - "norm"
  - "npcap"
  - "ntv2"
  - "nuklear"
  - "numcpp"
  - "nuraft"
  - "nvtx"
  - "oatpp-libressl"
  - "oatpp-openssl"
  - "oatpp-postgresql"
  - "oatpp-sqlite"
  - "oatpp-swagger"
  - "oatpp-websocket"
  - "oatpp"
  - "objectbox"
  - "oboe"
  - "observer-ptr-lite"
  - "octo-encryption-cpp"
  - "octo-keygen-cpp"
  - "octo-logger-cpp"
  - "octo-wildcardmatching-cpp"
  - "octomap"
  - "odbc"
  - "ode"
  - "ogg"
  - "onedpl"
  - "onetbb":
    - folders: ["all"]
  - "oniguruma"
  - "onnx"
  - "open-dis-cpp"
  - "open62541"
  - "openal-soft"
  - "openal"
  - "openapi-generator"
  - "opencl-headers"
  - "opencl-icd-loader"
  - "opencv"
  - "opencv"
  - "opencv"
  - "openddl-parser"
  - "openexr"
  - "openexr"
  - "openfbx"
  - "opengl-registry"
  - "opengl"
  - "opengrm"
  - "opengv"
  - "openh264"
  - "openjdk"
  - "openjpeg"
  - "openmesh"
  - "openssl"
  - "opentelemetry-cpp"
  - "openxlsx"
  - "optional-lite"
  - "opus"
  - "opusfile"
  - "orcania"
  - "osmanip"
  - "out_ptr"
  - "p7zip"
  - "paho-mqtt-c"
  - "parallel-hashmap"
  - "parson"
  - "pcg-cpp"
  - "pcre"
  - "pcre2"
  - "pdqsort"
  - "perfetto"
  - "perlinnoise"
  - "pffft"
  - "pfr"
  - "pgm-index"
  - "physfs"
  - "picobench"
  - "picojson"
  - "picosha2"
  - "pistache"
  - "pixman"
  - "pkgconf"
  - "platform.interfaces"
  - "plf_colony"
  - "plf_indiesort"
  - "plf_list"
  - "plf_nanotimer"
  - "plf_queue"
  - "plf_stack"
  - "plog"
  - "plutovg"
  - "pngpp"
  - "poco"
  - "podofo"
  - "poly2tri"
  - "polylabel"
  - "polylineencoder"
  - "polymorphic_value"
  - "poppler-data"
  - "proj"
  - "prometheus-cpp"
  - "protobuf"
  - "protopuf"
  - "protozero"
  - "psimd"
  - "psyinf-gmtl"
  - "ptex"
  - "pthreadpool"
  - "pugixml"
  - "pulseaudio"
  - "pybind11"
  - "pystring"
  - "qarchive"
  - "qcbor"
  - "qcustomplot"
  - "qhull"
  - "qpdf"
  - "qpoases"
  - "qr-code-generator"
  - "qtxlsxwriter"
  - "quantlib"
  - "quazip"
  - "quickjs"
  - "quill"
  - "quirc"
  - "qwt"
  - "qxlsx"
  - "r8brain-free-src"
  - "rabbitmq-c"
  - "range-v3"
  - "rapidcsv"
  - "rapidjson"
  - "rapidxml"
  - "rapidyaml"
  - "re2"
  - "reactiveplusplus"
  - "read-excel"
  - "recastnavigation"
  - "reckless"
  - "redis-plus-plus"
  - "refl-cpp"
  - "restbed"
  - "restinio"
  - "ring-span-lite"
  - "roaring"
  - "robin-hood-hashing"
  - "rotor"
  - "rply"
  - "rtmidi"
  - "rttr"
  - "runtimeqml"
  - "rxcpp"
  - "safeint"
  - "sail"
  # - "samarium"
  - "scnlib"
  - "scope-lite"
  - "screen_capture_lite"
  - "sdbus-cpp"
  - "sdf"
  - "sdl"
  - "sdl_image"
  - "sdl_net"
  - "sdl_ttf"
  - "seasocks"
  - "semver.c"
  - "sentry-breakpad"
  - "sentry-crashpad"
  - "sentry-native"
  - "serd"
  - "sfml"
  - "shapelib"
  - "simdjson"
  - "simdutf"
  - "sml"
  - "snappy"
  - "sofa"
  - "sokol"
  - "sol2"
  - "sole"
  - "sophus"
  - "soundtouch"
  - "soxr"
  - "span-lite"
  - "spdlog"
  - "spectra"
  - "spirv-headers"
  - "spirv-tools"
  - "spix"
  - "spscqueue"
  - "spy"
  - "sqlite3"
  - "sqlite_orm"
  - "sqlitecpp"
  - "squirrel"
  - "status-value-lite"
  - "stb"
  - "stc"
  - "stduuid"
  - "strawberryperl"
  - "string-view-lite"
  - "strong_type"
  - "svector"
  - "symengine"
  - "szip"
  - "taglib"
  - "taocpp-operators"
  - "taocpp-sequences"
  - "taocpp-taopq"
  - "taocpp-tuple"
  - "taskflow"
  - "taywee-args"
  - "tcb-span"
  - "teemo"
  - "tensorflow-lite"
  - "tensorpipe"
  - "termcap"
  - "tesseract"
  - "tgc"
  - "theora"
  - "threadpool"
  - "thrift"
  - "tiny-aes-c"
  - "tiny-bignum-c"
  - "tiny-regex-c"
  - "tiny-utf8"
  - "tinycbor"
  - "tinyexr"
  - "tinygltf"
  - "tinyobjloader"
  - "tinyply"
  - "tinyspline"
  - "tinyxml"
  - "tinyxml2"
  - "tixi3"
  - "tl-expected"
  - "tl-function-ref"
  - "tl-optional"
  - "tl"
  - "tlx"
  - "tmx"
  - "tmxlite"
  - "tng"
  - "toml11"
  - "tomlplusplus"
  - "tracy"
  - "transwarp"
  - "trantor"
  - "trompeloeil"
  - "tscns"
  - "tsil"
  - "tsl-array-hash"
  - "tsl-hat-trie"
  - "tsl-hopscotch-map"
  - "tsl-ordered-map"
  - "tsl-robin-map"
  - "tsl-sparse-map"
  - "tuplet"
  - "ulfius"
  - "uncrustify"
  - "uni-algo"
  - "unicorn"
  - "units"
  - "univalue"
  - "unordered_dense"
  - "unqlite"
  - "uriparser"
  - "utf8.h"
  - "utf8proc"
  - "utfcpp"
  - "uwebsockets"
  - "v-hacd"
  - "valijson"
  - "variant-lite"
  - "vc"
  - "vcglib"
  - "vectorclass"
  - "vectorial"
  - "veque"
  - "vk-bootstrap"
  - "volk"
  - "vorbis"
  - "voropp"
  - "vulkan-headers"
  - "vulkan-loader"
  - "vulkan-memory-allocator"
  - "vulkan-validationlayers"
  - "wasmedge"
  - "wasmer"
  - "wasmtime-cpp"
  - "wasmtime"
  - "watcher"
  - "wavelet_buffer"
  - "wayland-protocols"
  - "wayland"
  - "websocketpp"
  - "wildmidi"
  - "winflexbison"
  - "winmd"
  - "wslay"
  - "wyhash"
  - "xbyak"
  - "xerces-c"
  - "xkbcommon"
  - "xkeyboard-config"
  - "xlnt"
  - "xmlsec"
  - "xnnpack"
  - "xorg-cf-files"
  - "xorg-gccmakedep"
  - "xorg-macros"
  - "xorg-makedepend"
  - "xorg-proto"
  - "xorg"
  - "xorstr"
  - "xpack"
  - "xproperty"
  - "xqilla"
  - "xsimd"
  - "xtensor"
  - "xtl"
  - "xtrans"
  - "xxhash"
  - "xz_utils"
  - "yaclib"
  - "yaml-cpp"
  - "yasm"
  - "yder"
  - "yyjson"
  - "zeromq"
  - "zfp"
  - "zimg"
  - "zint"
  - "zlib-ng"
  - "zlib"
  - "zmarok-semver"
  - "zmqpp"
  - "zopfli"
  - "zpp_bits"
  - "zpp_throwing"
  - "zstd"
  - "zstr"
  - "zulu-openjdk"
  - "zxing-cpp"
  - "zziplib"
